# Generated by Django 5.0.4 on 2024-04-21 19:31

import referall.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('auth_code', models.CharField(blank=True, max_length=4)),
                ('invite_code', models.CharField(default=referall.models.generate_invite_code, max_length=6, unique=True)),
                ('activated_invite_code', models.CharField(blank=True, max_length=6)),
                ('invited_users', models.ManyToManyField(blank=True, related_name='invited_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
